language: erlang
otp_release:
  - 17.1
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.1/Precompiled.zip -O elixir.zip
  - unzip -d elixir elixir.zip
  - export PATH=$(pwd)/elixir/bin:$PATH
  - mix do local.hex --force, local.rebar
  - mix do deps.get, deps.compile, compile
script:
  - mix test
notifications:
  recipients:
    - martin@schuerrer.org
