language: elixir
elixir:
  - 1.2.0-rc.0
otp_release:
  - 18.0
  - 18.1
sudo: false # to use faster container based build environment
script:
  - mix test
notifications:
  recipients:
    - martin@pspdfkit.com
